import type { Order } from "../rules/types";
import { addDays, todayKey } from "./dates";

// 首次打开时灌入的演示数据，日期相对“今天”生成，保证排期台打开就有内容。

export function seedOrders(): Order[] {
  const today = todayKey();
  const tomorrow = addDays(today, 1);
  const createdAt = (d: string) => `${d}T08:30`;

  return [
    {
      id: "ORD-106",
      customer: "王雪",
      phone: "138-0000-1066",
      brand: "Burton Custom",
      lengthCm: 156,
      boardType: "全地域",
      services: ["edge", "wax"],
      waxType: "低温蜡",
      pickupAt: `${today}T18:00`,
      preferredTechId: "T1",
      price: 200,
      priceConfirmed: true,
      schedule: {
        date: addDays(today, -1),
        slot: "midday",
        techId: "T1",
        potId: "P1",
        stationId: "W1",
      },
      completion: {
        sideEdgeDeg: "88°",
        baseEdgeDeg: "1°",
        waxTempC: "115",
        baseRepairResult: "",
        completedAt: `${addDays(today, -1)}T16:40`,
      },
      createdAt: createdAt(addDays(today, -2)),
    },
    {
      id: "ORD-108",
      customer: "刘畅",
      phone: "139-0000-1088",
      brand: "Head Worldcup",
      lengthCm: 165,
      boardType: "竞速板",
      services: ["edge", "wax", "baseRepair"],
      waxType: "热蜡",
      pickupAt: `${today}T12:00`,
      preferredTechId: "T2",
      price: 492,
      priceConfirmed: true,
      schedule: {
        date: addDays(today, -1),
        slot: "morning",
        techId: "T2",
        potId: "P3",
        stationId: "W3",
      },
      completion: {
        sideEdgeDeg: "87°",
        baseEdgeDeg: "0.75°",
        waxTempC: "140",
        baseRepairResult: "板底两处深划痕已用 P-Tex 填补并打磨平整",
        completedAt: `${addDays(today, -1)}T11:50`,
      },
      createdAt: createdAt(addDays(today, -3)),
    },
    {
      id: "ORD-112",
      customer: "张磊",
      phone: "137-0000-1122",
      brand: "Salomon Huck Knife",
      lengthCm: 152,
      boardType: "公园板",
      services: ["edge", "wax"],
      waxType: "全温蜡",
      pickupAt: `${today}T18:30`,
      preferredTechId: "T1",
      price: 230,
      priceConfirmed: true,
      schedule: {
        date: today,
        slot: "morning",
        techId: "T1",
        potId: "P2",
        stationId: "W2",
      },
      completion: null,
      createdAt: createdAt(addDays(today, -1)),
    },
    {
      id: "ORD-115",
      customer: "孙悦",
      phone: "136-0000-1155",
      brand: "Rossignol XV",
      lengthCm: 158,
      boardType: "粉雪板",
      services: ["baseRepair"],
      waxType: null,
      pickupAt: `${today}T19:00`,
      preferredTechId: "T3",
      price: 165,
      priceConfirmed: true,
      schedule: {
        date: today,
        slot: "midday",
        techId: "T3",
        potId: null,
        stationId: null,
      },
      completion: null,
      createdAt: createdAt(addDays(today, -1)),
    },
    {
      id: "ORD-117",
      customer: "周明",
      phone: "135-0000-1177",
      brand: "Atomic Redster",
      lengthCm: 160,
      boardType: "竞速板",
      services: ["edge", "wax"],
      waxType: "热蜡",
      pickupAt: `${tomorrow}T12:00`,
      preferredTechId: "T2",
      price: 312,
      priceConfirmed: true,
      schedule: {
        date: today,
        slot: "midday",
        techId: "T2",
        potId: "P3",
        stationId: "W3",
      },
      completion: null,
      createdAt: createdAt(addDays(today, -1)),
    },
    {
      id: "ORD-119",
      customer: "吴迪",
      phone: "133-0000-1199",
      brand: "Nitro Team",
      lengthCm: 155,
      boardType: "全地域",
      services: ["wax"],
      waxType: "低温蜡",
      pickupAt: `${tomorrow}T18:00`,
      preferredTechId: "T1",
      price: 80,
      priceConfirmed: true,
      schedule: {
        date: tomorrow,
        slot: "morning",
        techId: "T1",
        potId: "P1",
        stationId: "W1",
      },
      completion: null,
      createdAt: createdAt(today),
    },
    {
      id: "ORD-121",
      customer: "郑楠",
      phone: "132-0000-1211",
      brand: "K2 Lime Lite",
      lengthCm: 148,
      boardType: "公园板",
      services: ["edge"],
      waxType: null,
      pickupAt: `${tomorrow}T20:00`,
      preferredTechId: "T2",
      price: null,
      priceConfirmed: false,
      schedule: null,
      completion: null,
      createdAt: createdAt(today),
    },
    {
      id: "ORD-123",
      customer: "冯涛",
      phone: "131-0000-1233",
      brand: "Dynastar M-Free",
      lengthCm: 168,
      boardType: "竞速板",
      services: ["edge", "wax", "baseRepair"],
      waxType: "热蜡",
      pickupAt: `${addDays(today, 2)}T18:00`,
      preferredTechId: "T3",
      price: 492,
      priceConfirmed: true,
      schedule: null,
      completion: null,
      createdAt: createdAt(today),
    },
  ];
}
